[workspace]
resolver = "2"
members = [
    "zest-core",
    "zest-theme",
    "zest-widget",
    "zest-simulator",
    "zest",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "GPL-3.0-or-later"
repository = "https://github.com/bhh32/zest"
authors = ["Bryan H. <bhh32@protonmail.com>"]

[workspace.dependencies]
embedded-graphics = { version = "0.8", default-features = false }
embedded-graphics-core = { version = "0.4", default-features = false }

zest-core = { path = "zest-core", version = "0.1.0" }
zest-theme = { path = "zest-theme", version = "0.1.0" }
zest-widget = { path = "zest-widget", version = "0.1.0" }
zest-simulator = { path = "zest-simulator", version = "0.1.0" }

[workspace.lints.rust]
missing_docs = "warn"
unsafe_code = "forbid"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
module_name_repetitions = "allow"
must_use_candidate = "allow"
missing_errors_doc = "allow"
needless_pass_by_value = "allow"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
